version: '3.1'

services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command: --configFile=/etc/traefik/traefik.yml
    environment:
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.exposedbydefault=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - acme:/acme:rw
      - ./traefik/conf:/conf:ro

    networks:
      - wp_network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"



  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=rootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/mysql
    networks:
      - wp_network

  wordpress_cli:
    image: wordpress:cli
    container_name: wordpress_cli
    user: root
    depends_on:
      db :
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      DOMAIN: ${DOMAIN}
    command: /wp-cli/wp-init.sh
    volumes:
      - wordpress:/var/www/html
      - ./themes/yith-wonder.zip:/var/www/html/wp-content/themes/yith-wonder.zip
      - ./wp-cli:/wp-cli
    labels:
      - "traefik.enable=false"
    networks:
      - wp_network

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=web-secure"
      - "traefik.http.routers.wordpress.rule=Host(`wpvp.${DOMAIN}`)"
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=myresolver
 
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadminvp.${DOMAIN}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web-secure"
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.tls.certresolver=myresolver
 
    networks:
      - wp_network

volumes:
  wordpress:
  db:
  acme:

networks:
  wp_network:
    name: wp_network