SERVER_IP = "192.168.56.110"
SERVER_NAME = "viportenS"
cpus           = ENV['CPUS'] || 2
memory         = ENV['MEMORY'] || 2048
BOX            = ENV['VERSION'] || "bento/ubuntu-20.04"

Vagrant.configure("2") do |config|

        config.vm.box = BOX
        config.vm.provider "virtualbox" do |vb|
          vb.memory = memory # Need to up the size or vboxmanage return an error
          vb.cpus = cpus
        config.vm.synced_folder "./App", "/home/vagrant/App"
        config.vm.network "forwarded_port", guest: 80, host: 80
        config.vm.network "forwarded_port", guest: 8080, host: 8080
        config.vm.network "forwarded_port", guest: 443, host: 443
        config.vm.network "forwarded_port", guest: 8081, host: 8081
    
        end

        config.vm.define SERVER_NAME do |viportenS|
            viportenS.vm.hostname = SERVER_NAME
            viportenS.vm.synced_folder ".", "/vagrant"
            viportenS.vm.network "private_network", ip: SERVER_IP
            viportenS.vm.provision "shell", privileged: true, path: "./scripts/dep.sh", args: [SERVER_IP]
        end
    end